# **********************************************************************************************
# NOTE: Upload this file to: https://devboxdsc.blob.core.windows.net/dsc-files/dev-build-vscode
# **********************************************************************************************

---
$schema: https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0

  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage  # Corrected module name
      id: vsCode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
        ensure: Present
        useLatest: true
        arguments: "--silent --accept-package-agreements --accept-source-agreements"
