# **********************************************************************************************
# NOTE: Upload this file to: https://devboxdsc.blob.core.windows.net/dsc-files/dev-build-vscode
# **********************************************************************************************

---
properties:
  configurationVersion: 0.2.0

  resources:
    - resource: Microsoft.Winget.DSC/WinGetPackage
      id: vsCode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        ensure: Present
