properties:
  configurationVersion: 0.2.0

  resources:
    - resource: Microsoft.Winget.DSC/WingetPackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
