# WinGet DSC configuration for Visual Studio 2022 Professional with workloads
# Version 1.0
$schema: https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  resources:
    # Step 1: Install Visual Studio 2022 Professional
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vs2022pro
      directives:
        description: Install Visual Studio 2022 Professional
      settings:
        id: Microsoft.VisualStudio.2022.Professional
        source: winget
        ensure: Present
        useLatest: true

    # Step 2: Add workloads using VisualStudioDSC
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      id: vs2022pro-workloads
      directives:
        description: Add common workloads to Visual Studio 2022 Professional
      settings:
        ProductId: Microsoft.VisualStudio.Product.Professional
        ChannelId: VisualStudio.17.Release
        Components:
          - Microsoft.VisualStudio.Workload.NetWeb          # ASP.NET and web development
          - Microsoft.VisualStudio.Workload.Azure           # Azure development
          - Microsoft.VisualStudio.Workload.ManagedDesktop  # .NET desktop development
          - Microsoft.VisualStudio.Workload.Data            # Data storage and processing
        IncludeRecommended: true
        IncludeOptional: false
