$schema: "1.0"
name: "common-additional-applications"
userTasks:
  - name: ~/winget
    description: "Install Postman"
    parameters:
      package: Postman.Postman

  - name: ~/winget
    description: "Install Notepad++"
    parameters:
      package:  Notepad++.Notepad++
